---
# control
control:
  depth: '2'
  loss_mode: 'exact-physics'
  loss_commit: '0.1-0.0001'
  seq_length: '4-4'
# data
data_name: Turb
# model
model_name: convlstm
# experiment
num_workers: 0
init_seed: 0
num_experiments: 1
log_interval: 0.25
device: cuda
world_size: 1
resume_mode: 0
# other
fig_format: png
